<?php

namespace Proxies\__CG__\Pidev\FrontOfficeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evenement extends \Pidev\FrontOfficeBundle\Entity\Evenement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Pidev\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'id', '' . "\0" . 'Pidev\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'titre', '' . "\0" . 'Pidev\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'lieu', '' . "\0" . 'Pidev\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'dateDebut', '' . "\0" . 'Pidev\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'dateFin', '' . "\0" . 'Pidev\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'confidentialite', '' . "\0" . 'Pidev\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'description', '' . "\0" . 'Pidev\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'prix', '' . "\0" . 'Pidev\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'type', '' . "\0" . 'Pidev\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'createur', '' . "\0" . 'Pidev\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'idClient', '' . "\0" . 'Pidev\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'participant');
        }

        return array('__isInitialized__', '' . "\0" . 'Pidev\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'id', '' . "\0" . 'Pidev\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'titre', '' . "\0" . 'Pidev\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'lieu', '' . "\0" . 'Pidev\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'dateDebut', '' . "\0" . 'Pidev\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'dateFin', '' . "\0" . 'Pidev\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'confidentialite', '' . "\0" . 'Pidev\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'description', '' . "\0" . 'Pidev\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'prix', '' . "\0" . 'Pidev\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'type', '' . "\0" . 'Pidev\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'createur', '' . "\0" . 'Pidev\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'idClient', '' . "\0" . 'Pidev\\FrontOfficeBundle\\Entity\\Evenement' . "\0" . 'participant');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Evenement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre($titre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', array($titre));

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', array());

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieu($lieu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieu', array($lieu));

        return parent::setLieu($lieu);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieu', array());

        return parent::getLieu();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDebut($dateDebut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDebut', array($dateDebut));

        return parent::setDateDebut($dateDebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDebut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDebut', array());

        return parent::getDateDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFin($dateFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFin', array($dateFin));

        return parent::setDateFin($dateFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFin', array());

        return parent::getDateFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfidentialite($confidentialite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfidentialite', array($confidentialite));

        return parent::setConfidentialite($confidentialite);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfidentialite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfidentialite', array());

        return parent::getConfidentialite();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix($prix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', array($prix));

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', array());

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateur(\Pidev\FrontOfficeBundle\Entity\Utilisateur $createur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateur', array($createur));

        return parent::setCreateur($createur);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateur', array());

        return parent::getCreateur();
    }

    /**
     * {@inheritDoc}
     */
    public function addIdClient(\Pidev\FrontOfficeBundle\Entity\Utilisateur $idClient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIdClient', array($idClient));

        return parent::addIdClient($idClient);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIdClient(\Pidev\FrontOfficeBundle\Entity\Utilisateur $idClient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIdClient', array($idClient));

        return parent::removeIdClient($idClient);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdClient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdClient', array());

        return parent::getIdClient();
    }

    /**
     * {@inheritDoc}
     */
    public function addParticipant(\Pidev\FrontOfficeBundle\Entity\Utilisateur $participant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addParticipant', array($participant));

        return parent::addParticipant($participant);
    }

    /**
     * {@inheritDoc}
     */
    public function removeParticipant(\Pidev\FrontOfficeBundle\Entity\Utilisateur $participant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeParticipant', array($participant));

        return parent::removeParticipant($participant);
    }

    /**
     * {@inheritDoc}
     */
    public function getParticipant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParticipant', array());

        return parent::getParticipant();
    }

}
