Abonnement:
    type: entity
    table: abonnement
    indexes:
        id_prest:
            columns:
                - id_prest
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: string
            nullable: false
            length: 20
            fixed: false
        dateDebut:
            type: date
            nullable: false
            column: date_debut
        dateFin:
            type: date
            nullable: false
            column: date_fin
    manyToOne:
        idPrest:
            targetEntity: Utilisateur
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_prest:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
