Reclamation:
    type: entity
    table: reclamation
    indexes:
        id_expediteur:
            columns:
                - id_expediteur
        id_expediteur_2:
            columns:
                - id_expediteur
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        date:
            type: datetime
            nullable: false
            default: CURRENT_TIMESTAMP
        contenu:
            type: text
            nullable: false
            length: 65535
            fixed: false
            column: Contenu
    manyToOne:
        idExpediteur:
            targetEntity: Utilisateur
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_expediteur:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
