Utilisateur:
    type: entity
    table: utilisateur
    indexes:
        id:
            columns:
                - id
        id_2:
            columns:
                - id
    uniqueConstraints:
        mail:
            columns:
                - mail
        cin:
            columns:
                - cin
        matricule_fiscal:
            columns:
                - matricule_fiscal
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 50
            fixed: false
        adresse:
            type: string
            nullable: false
            length: 50
            fixed: false
        mail:
            type: string
            nullable: false
            length: 50
            fixed: false
        tel:
            type: integer
            nullable: false
            unsigned: false
        dateInscrit:
            type: datetime
            nullable: true
            default: CURRENT_TIMESTAMP
            column: date_inscrit
        password:
            type: string
            nullable: false
            length: 50
            fixed: false
        prenom:
            type: string
            nullable: true
            length: 50
            fixed: false
        age:
            type: integer
            nullable: true
            unsigned: false
        cin:
            type: integer
            nullable: true
            unsigned: false
        matriculeFiscal:
            type: string
            nullable: true
            length: 50
            fixed: false
            column: matricule_fiscal
        description:
            type: text
            nullable: true
            length: 65535
            fixed: false
        nature:
            type: integer
            nullable: false
            unsigned: false
        etat:
            type: string
            nullable: false
            length: 20
            fixed: false
            default: active
    manyToMany:
        idOffre:
            targetEntity: Offre
            cascade: {  }
            mappedBy: idClient
            inversedBy: null
            joinTable: null
            orderBy: null
        idEvenement:
            targetEntity: Evenement
            cascade: {  }
            mappedBy: null
            inversedBy: idClient
            joinTable:
                name: evaluationevenement
                joinColumns:
                    -
                        name: id_client
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: id_evenement
                        referencedColumnName: id
            orderBy: null
        idClient:
            targetEntity: Utilisateur
            cascade: {  }
            mappedBy: idPrestataire
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
